apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: cicdsample
spec:
  tag: ccr.ccs.tencentyun.com/yanghaitao/cicdsample
  serviceAccount: service-account
  cacheSize: "1.5Gi"
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/Poseidon1979/cicd.git
      revision: a74837bccedcc67d037ae880ecf4232f91830904
      
